package com.digihealth.doc.sql;

public class DocPreVisitSql {
	public static final String insert = "insert into doc_pre_visit (preVisitId, regOptId, briefHis, "
			+ "comorbidity, drugAddiction, drugAddictionCond, "
			+ "othComorbidity, heartBool, lungbreath, "
			+ "allergic, allergicCond, medHis, "
			+ "diabetes, anaes, anaesCond, "
			+ "anaesHis, operHis, operHisCond, "
			+ "bloodPre, heartrate, breath, "
			+ "organNormal, organAbnormal, other1, "
			+ "preAnesEvaLevel, situationLevel, operationLevel, "
			+ "preAge, preAnesEvaLevel1, anaesDanger, "
			+ "other2, anaestheitistId, signDate, "
			+ "processState, anaesMonitor, anaesStep, "
			+ "gestationTime, heartBoolCond, heartBoolRegion, "
			+ "heartBoolOther, lungbreathCond, lungbreathOther, "
			+ "brainNerve, brainNerveOther, spineLimb, "
			+ "paraplegia, spineLimbOther, limbDyskinesia, "
			+ "limbDyskinesiaOther, blood, bloodOther, "
			+ "kidney, kidneyCond, kidneyOther, "
			+ "digestion, digestionOther, endocrine, "
			+ "endocrineOther, infectious, infectiousOther, "
			+ "alcoholism, alcoholismTime, alcoholismFreq, "
			+ "smoking, smokingTime, smokingFreq, "
			+ "specialTreatment, specialTreatmentCond, "
			+ "vitalSignsAbnormal, awareness, mallampatis, "
			+ "bonesPitch, neckRestricted, cardiothoracicAbnormal, "
			+ "toothAbnormal, toothAbnormalCond, toothAbnormalOther, "
			+ "motionAbnormal, allensTest, physicalOther, "
			+ "assayAbnormal, assayAbnormalCond, assayAbnormalOther, "
			+ "videographyAbnormal, ECGAbnormal, auxiliaryOther, "
			+ "asa, nyha, specialcasePrecautions, "
			+ "designedAnaesCode, designedAnaes, airwayManage, "
			+ "specialHandle, analgesic, analgesicCond, "
			+ "monitor, leaveTo, evaluationOther, "
			+ "otherBriefHisCond, tracheaOffset, ucgAbnormal, "
			+ "ef, otherProblem, otherMeasures, "
			+ "hypertension, coronary, airwayPatency, "
			+ "anaesPuncture, anaesPunctureCond, anesthIndica, "
			+ "anaesDocord, assistMeasure, asaE, "
			+ "organAbnormalGrade, glaucoma, specialTreatmentOther, riskAssessment, "
			+ "heartBoolHave, lungbreathHave, brainNerveHave, spineLimbHave, bloodHave, "
			+ "kidneyHave, digestionHave, endocrineHave, infectiousHave, drugAbuseCond, anaesMethod, anaesMethodCode) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

	public static final String deleteByRegOptId = "DELETE FROM doc_pre_visit WHERE regOptId IN(SELECT t.regOptId FROM bas_reg_opt t WHERE t.beid = ? AND t.name LIKE ?)";
}
